### ISSUE TITLE
Hero: Improve pattern quality

### ISSUE THREAD

**Issue by pahupe** [urfuwo/hlx-test#321]
Hero background pattern images are shown in lower quality than expected

Ref: https://adobe-dx-support.slack.com/archives/C06H8UNQ3RS/p1710760013243169

Ideas:
- For pattern background images, use format webpll (loss-less) instead of webply (lossy). But don't use this format for images (see comments by @rootpea below)

**Comment by rootpea** [comment]
@pahupe  The current URL encoding is correct and does not need to be changed.

The second URL here:
`https://main--hlx-test--urfuwo.hlx.page/draft/skhare/media_1f1b0e7bd9fc44faab3f2018e58f7eb06e299f1df.png?width=2000&#x26;format=webply&%23x26;optimize=medium`
is incorrectly encoded and should not be used.
Since the URL is incorrect, a fallback high quality 15KB PNG is served instead of the low quality 1KB WEBP file.

**Comment by pahupe** [comment]
@rootpea : I am having difficulties understanding. Ultimately, we want to render images in acceptable quality. You're saying the "correct" URL renders a poor quality version of the background with a lot of artifacts, whereas the "incorrect" URL renders a better quality image.

If that's not the way to go, then what is the best way to ensure we deliver images of acceptable quality?

**Comment by pahupe** [comment]
I renamed it to "Improve image quality" as the focus has shifted

**Comment by rootpea** [comment]
> If that's not the way to go, then what is the best way to ensure we deliver images of acceptable quality

if we want png, we should explicitly specify png and not depend on fallback behaviour because the webp format was incorrectly specified

**Comment by rootpea** [comment]
> If that's not the way to go, then what is the best way to ensure we deliver images of acceptable quality?

webp has these formats that can request
webpll	WebP (Lossless)
webply	WebP (Lossy)


webply is not appropriate for line drawings such as the hero background

we need either webpll, or png for line drawings
